### PR TITLE
Switch to LGPLv2.1+

### PR DESCRIPTION
**Pull request by IAlibay**
Whilst the original code contribution has been accepted as LGPLv2.1+, we have to relicense this MDAKit.

- [x] We have a contribution from @rodpollet which does not have a relicensing agreement, which we will need before merging this PR.

PR Checklist
------------
 - [x] CHANGELOG updated?

### CODE REVIEW

**Review by orbeckst — APPROVED** [review]
I agree to the relicensing under LGPLv2.1+.

I'll try to contact @rodpollet . I am blocking until we have their agreement.

**Comment by IAlibay** [comment]
@orbeckst I've just emailed @rodpollet 

Also I'm going to ignore the windows failures for now - I believe these will fix themselves once we release a new version of MDAnalysis.

**Comment by IAlibay** [comment]
@fiona-naughton @ianmkenney if you can approve the relicense this would be great.

**Review by orbeckst — CHANGES_REQUESTED** [review]
Block until we have @rodpollet 's agreement to the license change.

**Review by fiona-naughton — APPROVED** [review]

**Review by ianmkenney — APPROVED** [review]

**Comment by fiona-naughton** [comment]
Just noticed that the license is also mentioned in `README.md` under the "Copyright" section, so it also needs to be updated there (pathsimanaysis and mdahole2 both also have the old license info in the README, I can make a quick some PRs for them)

**Comment by orbeckst** [comment]
Well spotted—thanks for fixing!Am 11/22/24 um 21:27 schrieb Fiona Naughton ***@***.***>:﻿
Just noticed that the license is also mentioned in README.md under the "Copyright" section, so it also needs to be updated there (pathsimanaysis and mdahole2 both also have the old license info in the README, I can make a quick some PRs for them)

**Comment by IAlibay** [comment]
> Just noticed that the license is also mentioned in `README.md` under the "Copyright" section, so it also needs to be updated there (pathsimanaysis and mdahole2 both also have the old license info in the README, I can make a quick some PRs for them)

This is done thanks.

**Comment by IAlibay** [comment]
@orbeckst we have the agreement, are you ok to approve?

**Review by orbeckst — APPROVED** [review]

**Pull request merged**
