### PR TITLE
Added PyPI deployment workflow

### PR DESCRIPTION
**Pull request by ianmkenney**

### CODE REVIEW

**Review by orbeckst — CHANGES_REQUESTED** [review]
Thanks Ian! Sorry for the terse review:

- [ ] Fix the dependencies in https://github.com/MDAnalysis/waterdynamics/blob/8f58202a418d5d4937e3095f5f80838c235c54e8/pyproject.toml#L20-L21 (and in the devtools test env) to explicitly include all external packages (no implicitly relying on MDAnalysis to pull in deps) — I _think_ it's only numpy but please double-check.
- [ ] Update the docs  (README, sphinx docs) to include pip installation instructions.

We can then merge it and do a 0.1.0 test release.

**Comment by ianmkenney** [comment]
It looks like just numpy

**Review by orbeckst — APPROVED** [review]
This _looks_ ok to me, so I think we should just test it with an initial release tag and see if it works with testpypi.

**Review by orbeckst — CHANGES_REQUESTED** [review]
You forgot https://github.com/MDAnalysis/waterdynamics/blob/main/devtools/conda-envs/test_env.yaml

**Comment by ianmkenney** [comment]
I'm not sure how to only do test pypi. Also this repo differs from PSA in that I manually uploaded to PyPI first, so the initial release might fail if it doesn't make the project for us

**Comment by orbeckst** [comment]
I think you first have to create the project.

> I'm not sure how to only do test pypi.

What I meant is that the workflow will trigger the testpypi deployment once you tag the branch. Then do a manual installation from testpypi (`pip install ... waterdynamics` — it tells you on the testpypi page what the exact command is) and run the tests to check that the package works. 

Once you've manually checked that testpypi works, make the GitHub release to trigger deployment to pypi. Manually check the pypi package (because we're paranoid) and if that goes well, too, we are pretty sure that it will also work in the future. (Well, we'll learn from the MDAKit registry if not.)

**Review by orbeckst — APPROVED** [review]

**Pull request merged**
